Parameters:
  ConnectLambdaArn:
    Type: String
  DisconectLambdaArn:
    Type: String
  SendMessageLambdaArn:
    Type: String

Resources:
  ChatWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ChatWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: '$request.body.action'
      Description: Real-time chat WebSocket API

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref ConnectLambdaArn
      IntegrationMethod: POST
      PayloadFormatVersion: '1.0'

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref DisconectLambdaArn
      IntegrationMethod: POST
      PayloadFormatVersion: '1.0'

  SendMessageIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref SendMessageLambdaArn
      IntegrationMethod: POST
      PayloadFormatVersion: '1.0'

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub integrations/${ConnectIntegration}

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub integrations/${DisconnectIntegration}

  SendMessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: sendMessage
      AuthorizationType: NONE
      Target: !Sub integrations/${SendMessageIntegration}

  ChatWebSocketApiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref ChatWebSocketApi
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - SendMessageRoute

  ChatWebSocketApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: prod
      ApiId: !Ref ChatWebSocketApi
      DeploymentId: !Ref ChatWebSocketApiDeployment
      AutoDeploy: true

Outputs:
  WebSocketApiId:
    Description: WebSocket API ID
    Value: !Ref ChatWebSocketApi
    Export:
      Name: ChatWebSocketApiId

  WebSocketApiEndpoint:
    Description: WebSocket API Endpoint
    Value: !Sub wss://${ChatWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/prod
    Export:
      Name: ChatWebSocketApiEndpoint
