# ---------------------------------------------------------------------
# 🧠 Root Stack Purpose:
# Orchestrates nested stack for Cognito with Google OAuth integration.
#
# Responsibilities:
#   1. Pass Google OAuth credentials and stage to nested Cognito stack
#   2. Deploys the complete Cognito OAuth2 login system
# ---------------------------------------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Root stack for creating a passwordless login system using Google OAuth 2.0 and Cognito.
  This stack launches the nested stack that builds the Cognito infrastructure and sets up
  Google as the only identity provider.

Parameters:

  Stage:
    Type: String
    Default: dev
    Description: Deployment stage (dev, qa, prod)

  DeploymentBucket:
    Type: String
    Description: S3 bucket that contains the nested stack template

  GoogleClientId:
    Type: String
    Description: OAuth Client ID from Google Cloud Console

  GoogleClientSecret:
    Type: String
    Description: OAuth Client Secret from Google Cloud Console

Resources:

  CognitoGoogleAuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${DeploymentBucket}.s3.${AWS::Region}.amazonaws.com/services/cognito/nested-cognito-google-auth-stack.yaml
      Parameters:
        Stage: !Ref Stage
        GoogleClientId: !Ref GoogleClientId
        GoogleClientSecret: !Ref GoogleClientSecret

Outputs:

  CognitoNestedStackId:
    Description: ID of the nested Cognito OAuth stack
    Value: !Ref CognitoGoogleAuthStack
